-- MySQL Script generated by MySQL Workbench
-- Wed Jan 20 22:05:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kanban
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kanban
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kanban` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `kanban` ;

-- -----------------------------------------------------
-- Table `kanban`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kanban`.`Departments` ;

CREATE TABLE IF NOT EXISTS `kanban`.`Departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kanban`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kanban`.`Roles` ;

CREATE TABLE IF NOT EXISTS `kanban`.`Roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `cost_rate` DECIMAL(15,2) NULL DEFAULT NULL,
  `bill_rate` DECIMAL(15,2) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kanban`.`People`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kanban`.`People` ;

CREATE TABLE IF NOT EXISTS `kanban`.`People` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `RoleId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `RoleId` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `people_ibfk_1`
    FOREIGN KEY (`RoleId`)
    REFERENCES `kanban`.`Roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kanban`.`Projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kanban`.`Projects` ;

CREATE TABLE IF NOT EXISTS `kanban`.`Projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `DepartmentId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `DepartmentId` (`DepartmentId` ASC) VISIBLE,
  CONSTRAINT `projects_ibfk_1`
    FOREIGN KEY (`DepartmentId`)
    REFERENCES `kanban`.`Departments` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kanban`.`States`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kanban`.`States` ;

CREATE TABLE IF NOT EXISTS `kanban`.`States` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kanban`.`Tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kanban`.`Tasks` ;

CREATE TABLE IF NOT EXISTS `kanban`.`Tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `hours` INT NULL DEFAULT NULL,
  `cost` DECIMAL(15,2) NULL DEFAULT NULL,
  `revenue` DECIMAL(15,2) NULL DEFAULT NULL,
  `billable` TINYINT(1) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `PersonId` INT NULL DEFAULT NULL,
  `ProjectId` INT NULL DEFAULT NULL,
  `StateId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `PersonId` (`PersonId` ASC) VISIBLE,
  INDEX `ProjectId` (`ProjectId` ASC) VISIBLE,
  INDEX `StateId` (`StateId` ASC) VISIBLE,
  CONSTRAINT `tasks_ibfk_1`
    FOREIGN KEY (`PersonId`)
    REFERENCES `kanban`.`People` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tasks_ibfk_2`
    FOREIGN KEY (`ProjectId`)
    REFERENCES `kanban`.`Projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tasks_ibfk_3`
    FOREIGN KEY (`StateId`)
    REFERENCES `kanban`.`States` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
